# 環境設定

FOLDER_PICTURE = r'C:\workspace\picture'
PICTURE_OK = FOLDER_PICTURE + r'\OKbutton.png'
PICTURE_OK2 = FOLDER_PICTURE + r'\OK2.png'

# 召喚石
PICTURE_SUMMONXXX = FOLDER_PICTURE + r'\XXX.png'

TWITTER_BEARER_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

# 検索ワード
KEYWORD = {'query': 'XXXXXXXXXXXXXXXXXXXXXXX'}

